### PR TITLE
Fix issue #1: Resolved the problem with the User Menu button not closing

### LINKED ISSUE #1: User Menu button not closing when clicked again.
## Description:

When interacting with the User Menu button on the website, there is an issue where the menu does not close when clicked again. After opening the menu, clicking on the button again should toggle the visibility of the menu, allowing users to close it. However, in the current state, the menu remains open, and users have to click outside of the menu to make it disappear. This behavior disrupts the expected flow and user experience. The issue can be observed on the homepage or pages that display the header with the User Menu button. Implementing a toggle functionality for the User Menu button could provide a solution and ensure a consistent and intuitive user experience.

##  Steps to Reproduce:

Visit the website.
Scroll to the User Menu button located in the top right corner of the page.
Click on the User Menu button to open the menu.
Observe that the menu opens and displays the options correctly.
Click on the User Menu button again to close the menu.
Notice that the menu does not disappear and remains open.

## Expected Behavior:

The User Menu button should toggle the display of the menu, closing it when clicked again after opening.

## Actual Behavior:

The User Menu button only opens the menu but does not close it when clicked again. Users have to click outside of the menu to make it disappear.

## Possible Solution:

Implement a toggle functionality for the User Menu button. When clicked, it should alternate between opening and closing the menu, providing a better user experience.

### PR DESCRIPTION
**Pull request by Aadhi13**
## Description
This pull request addresses the issue raised in #1, where the User Menu button did not close when clicked again. I have implemented a fix that ensures the menu toggles properly upon subsequent clicks, providing a better user experience.

## Changes Made

- Updated event handling to correctly toggle the visibility of the menu.
- Tested the changes to verify the desired behavior.

## Testing

I have thoroughly tested the changes locally to ensure the User Menu button now closes when clicked again. I have also verified that the menu behavior remains consistent with the expected user flow.

## Related Issues

Closes #1

### CODE REVIEW

File: client/src/components/user/Header/Header.jsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ function Header() {
             </button>
             <div className='flex items-center px-2'><input onFocus={() => setSearchBoxFocus(true)} onBlur={() => setSearchBoxFocus(false)} className='outline-none  pl-1 w-80' id='searchBox' placeholder='Search' type="text" /></div>
           </div>
-          <div className='flex border items-center gap-2 border-gray-300 rounded-full py-2 px-4' onClick={(e) => { e.stopPropagation(); setMenu(true) }}>
```
Comment (Aadhi13) [inline client/src/components/user/Header/Header.jsx:39]: This logic is currently designed to function in one direction only.

File: client/src/components/user/Header/Header.jsx [hunk 2]
```diff
@@ -36,7 +36,7 @@ function Header() {
...
+          <div className='flex border items-center gap-2 border-gray-300 rounded-full py-2 px-4' onClick={(e) => { e.stopPropagation(); setMenu(!menu) }}>
```
Comment (Aadhi13) [inline client/src/components/user/Header/Header.jsx:39]: Now it is functioning in both directions by reversing the menu state (true/false) to its opposite value.
